/* Laurence Mirabal
 * MirabalP8 Database
 * lmirabal3@cnm.edu
 * DBFrame.java
 * 12/1/2011
*/

package mirabalp8;

/**
 *
 * @author Laurence PC
 */
public class DBFrame extends javax.swing.JFrame {

    private DBManager dbm;
    private NewPanel newp;
    private EditPanel editp;
    private DeletePanel deletep;

    /** Creates new form DBFrame */
    //DBFrame panels added
    public DBFrame() {
        initComponents();
        //each panel gets overloaded with the DBManager
        dbm = new DBManager();
        newp = new NewPanel(dbm);
        add(newp);      
        editp = new EditPanel(dbm);
        add(editp);       
        deletep = new DeletePanel(dbm);
        add(deletep);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MirabalP8 Digital Camera Database");
        setMinimumSize(new java.awt.Dimension(650, 420));
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
