/* Laurence Mirabal
 * MirabalP8 Database
 * lmirabal3@cnm.edu
 * DeletePanel.java
 * 12/1/2011
*/
package mirabalp8;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Laurence PC
 */
public class DeletePanel extends javax.swing.JPanel {
    //call dbmanager
    private DBManager dbm;
    //create list array for the jlist box
    private String[] list;
    //put the list into a record array to display
    private String[] rec;
    //my variables in my table
    private String cName, model, megapix, price;
    private int UID;

    /** Creates new form DeletePanel */
    public DeletePanel(DBManager db) {
        initComponents();
        dbm = db;

        try
        {
            list = dbm.getList();
        }
        catch(SQLException ex)
        {//catch exception
         Logger.getLogger(DeletePanel.class.getName()).log(Level.SEVERE,null,ex);
        }
        DefaultListModel listModel = new DefaultListModel();
        for(int i =0; i < list.length; i++)
        {
            listModel.addElement(list[i]);
        }
        jList1.setListData(list);
    }

    public void reloadList()
    {
        try
        {
            list = dbm.getList();
        }
        catch(SQLException ex)
        {//catch exception
         Logger.getLogger(DeletePanel.class.getName()).log(Level.SEVERE,null,ex);
        }
        DefaultListModel listModel = new DefaultListModel();
        for(int i = 0; i < list.length; i++)
        {
            listModel.addElement(list[i]);
        }
        jList1.setListData(list);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabelCName = new javax.swing.JLabel();
        jLabelModel = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelMP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        setMinimumSize(new java.awt.Dimension(179, 420));
        setPreferredSize(new java.awt.Dimension(179, 420));

        jButtonDelete.setText("Delete Record");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Manufacturer");

        jLabel3.setText("Model  #");

        jLabel4.setText("Price  $");

        jLabel5.setText("Megapixels");

        jButton1.setText("Refresh List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelMP, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelete)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        try
        {
        if(!evt.getValueIsAdjusting())
        {
            int[] IDs;
            try 
            {
                IDs = dbm.getIDs();
            } 
            catch (SQLException ex) 
            {//catch exception
        Logger.getLogger(DeletePanel.class.getName()).log(Level.SEVERE,null,ex);
                IDs = new int[0];
            }
            int index = jList1.getSelectedIndex();

            UID = IDs[index];

            try
            {
                rec = dbm.getRecord(UID);
            }
            catch (SQLException ex) 
            {//catch exception
        Logger.getLogger(DeletePanel.class.getName()).log(Level.SEVERE,null,ex);
                 rec = new String[0];
            }

            cName = rec[1];  jLabelCName.setText(cName);
            model = rec[2];  jLabelModel.setText(model);
            megapix = rec[3]; jLabelMP.setText(megapix);
            price = rec[4]; jLabelPrice.setText(price);
           }
         }
        catch(Exception e)
         {
     Logger.getLogger(DeletePanel.class.getName()).log(Level.SEVERE, null, e);
         }
         
    }//GEN-LAST:event_jList1ValueChanged

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if(!indexSelected())
        {
            int result = JOptionPane.showConfirmDialog(null,
                    "Are you sure you want to delete the record for " + cName +
                    "?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if(result == 0)
            {
                try
                {
                    dbm.delete(UID);
                    updateList();
                    clear();
                }
                catch (SQLException ex)
                {//catch exception
                 Logger.getLogger(DeletePanel.class.getName()).log(Level.SEVERE,
                     null,ex);
                    JOptionPane.showMessageDialog(null,
                          "Cannot delete file! \n" + ex.getMessage(),
                          "SQL Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null,
                    "You must make a selection to delete.",
                    "No Selection made", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateList()
    {//update list for the jList to display
        try {
            list = dbm.getList();
        }
        catch (SQLException ex)
        {//catch exception
      Logger.getLogger(DeletePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel listModel = new DefaultListModel();
        for(int i = 0; i < list.length; i++)
        {
            listModel.addElement(list[i]);
        }
        jList1.setListData(list);
    }
    
    private boolean indexSelected()
    {//identify which, if any, boxes are selected
        if(jList1.isSelectionEmpty())
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    private void clear()
    {//clear function to empty the text boxes
        jLabelCName.setText("");
        jLabelModel.setText("");
        jLabelMP.setText("");
        jLabelPrice.setText("");
        cName = "";
        model = "";
        megapix = "";
        price = "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCName;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
